spring:
  application:
    name: configserver
  profiles:
    active:
    # - native
    - git
  cloud:
    config:
      server:
       # native:
       #   search-locations:
         # - classpath:/config/
        #  - file:D:/MS-Workspace/config
          git:
            uri: "https://github.com/learncode/learncode-config.git"
            default-label: main
            timeout: 5
            clone-on-start: true
            force-pull: true
encrypt:
  key: 1234567890abcdef1234567890abcdef

server:
  port: 8071
